services:
  - type: web
    name: quiniela-liga-mx
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PLATFORM_PASSWORD
        sync: false
